local _, F = ...
local D = F.GuideDraft
-- Independently authored regional circuits; quest facts are sourced separately.
local function cycle(g, key, label, ids, note)
    D:Group(g,key.."-pickup",label..": accept","pickup",ids,nil,note)
    D:Group(g,key.."-objectives",label..": objectives","objective",ids,nil,note)
    D:Group(g,key.."-return",label..": turn in","turnin",ids,nil,note)
end
local function delivery(g, key, label, id)
    D:Group(g,key.."-pickup",label..": accept","pickup",{id})
    D:Group(g,key.."-return",label..": deliver","turnin",{id})
end
local function optional(g,key,label,ids,note)
    D:Note(g,key,label,note.." These quests are optional. Next continues the main route.")
    local step=g.steps[#g.steps]; step.alongside={}
    for _,id in ipairs(ids) do
        for _,kind in ipairs({"pickup","objective","turnin"}) do
            step.alongside[#step.alongside+1]=D:Task(kind,id,true)
        end
    end
end
local function entry(g,note)
    D:ClassStop(g,"entry-class",note.." Train your level-20 abilities and complete available class unlocks. Register flight points and set a convenient hearthstone. Next confirms this stop.")
end

local g=D:New("alliance-duskwood-20-30","Duskwood / Redridge 20-30","Duskwood",{"Human","High Order Skyborne"},20,30)
entry(g,"Travel from Lakeshire or Stormwind to Darkshire by the road. Avoid fighting higher-level enemies on the way.")
optional(g,"redridge-cleanup","Optional Lakeshire cleanup",{20,115,91,150},"Finish accepted Blackrock, shadowcaster, gnoll or murloc work before leaving Redridge. Check enemy levels; Stonewatch group work is a detour.")
D:Group(g,"darkshire-first-pickup","Darkshire: Night Watch, wolves, totem and western deliveries","pickup",{56,90,101,163,164,165})
cycle(g,"eastern-night-watch","Eastern graveyard: first Night Watch patrol",{56},"The Totem of Infliction can be collected alongside later undead circuits; keep its items.")
cycle(g,"road-wildlife","Western road: wolves and spiders",{226,245},"Take these from the road watchers. Collect wolf meat and spider venom for your accepted Darkshire quests as you travel.")
delivery(g,"raven-hill-intro","Deliver Raven Hill to Jitters",163)
delivery(g,"jitters-food","Take Jitters' request to Chef Grual",5)
cycle(g,"crab-cakes","Darkshire: prepare Jitters' food",{93})
delivery(g,"jitters-return","Return the food to Jitters",240)
delivery(g,"sven-supplies","Deliver supplies to Sven's camp",164)
delivery(g,"hermit-intro","Visit Abercrombie north of Raven Hill",165)
delivery(g,"hermit-supplies","Bring Abercrombie's supply request to Madame Eva",148)
delivery(g,"ghost-thread","Visit Blind Mary for the thread",149)
delivery(g,"return-comb","Return Blind Mary's comb",154)
delivery(g,"deliver-thread","Deliver the thread to Abercrombie",157)
delivery(g,"zombie-juice-request","Request zombie juice in Darkshire",158)
D:Group(g,"darkshire-second-pickup","Darkshire: rot blossoms, next Night Watch and Look to the Stars","pickup",{156,57,174})
D:Checkpoint(g,"duskwood-level23",23,"Finish the first patrol and western road work before taking on deeper graveyard packs. Complete useful accepted quests if you need XP.")
cycle(g,"rot-blossoms","Raven Hill: collect rot blossoms",{156},"Pull undead individually. Combine this with accepted Totem of Infliction collection; avoid dense crypt interiors if unsafe.")
delivery(g,"juice-delivery","Deliver the zombie juice to Abercrombie",159)
cycle(g,"ghoulish-effigy","Raven Hill: gather the effigy components",{133})
cycle(g,"night-watch-second","Continue the Night Watch patrol",{57})
D:Group(g,"darkshire-wildlife-return","Return the wolf cooking work","turnin",{90})
cycle(g,"stars-lens","Prepare the first Look to the Stars lens",{174},"This stage requires a Bronze Tube. Check a vendor, engineer or your bags; use Skip if obtaining it would mean a long detour.")
delivery(g,"stars-mary","Ask Blind Mary about the lens",175)
cycle(g,"stars-lens-return","Retrieve and return the lens",{177})
cycle(g,"sven-revenge","Investigate Sven's ruined farm",{95})
delivery(g,"sven-camp","Report back to Sven",230)
delivery(g,"shadowy-figure","Ask Madame Eva about the shadowy figure",262)
delivery(g,"shadowy-records","Consult Clerk Daltry",265)
delivery(g,"shadowy-inn","Ask at the inn",266)
delivery(g,"shadowy-jitters","Speak with Jitters at Raven Hill",453)
delivery(g,"shadowy-sven","Return the investigation to Sven",268)
D:ClassStop(g,"duskwood-train26","Combine a Stormwind training visit with accepted city deliveries. Keep your hearthstone useful for the remaining Darkshire circuits.")
D:Checkpoint(g,"duskwood-level26",26,"Finish useful nearby turn-ins before the worgen and ogre circuits. This checkpoint does not promise an exact quest XP total.")
cycle(g,"worgen-first","Southern woods: first worgen hunt",{173})
cycle(g,"worgen-second","Southern woods: second worgen hunt",{221})
cycle(g,"ogre-theft","Western ogre camp: recover Abercrombie's crate",{134},"Watch patrols and enemy levels. Skip if the camp is repeatedly unsafe solo.")
delivery(g,"mayor-note","Deliver Abercrombie's note to the mayor",160)
delivery(g,"translate-note","Take the note to Sirra Von'Indi",251)
cycle(g,"translation-wait","Wait for Sirra's translation",{401})
delivery(g,"translation-mayor","Return the translation to the mayor",252)
D:Checkpoint(g,"duskwood-level28",28,"The last patrol and ogre encounters are harder. Complete accepted tasks or optional circuits before attempting them.")
cycle(g,"night-watch-final","Finish the last Night Watch patrol",{58})
cycle(g,"stars-ogres","Ogre mound: recover the final star-gazing item",{181},"Check the camp before committing; retreat from multiple pulls and use Skip if needed.")
D:Group(g,"totem-return","Return the completed Totem of Infliction collection","turnin",{101})
optional(g,"duskwood-optional-final","Optional harder quests and beta discoveries",{222,223,253,96139,96137,96138},"Continue the worgen chain if suitable. Bride of the Embalmer is group content. Follow offered Valor-family discoveries only when available; dropped-item starts and beta prerequisites are not assumed.")
D:Finish(g,"duskwood","At 30, choose your next regional route when available. You can supplement this circuit with Wetlands or Ashenvale; 30-40 guides are not installed.")

g=D:New("alliance-wetlands-20-30","Wetlands 20-30","Wetlands",{"Dwarf","Gnome","High Order Skyborne"},20,30)
entry(g,"Enter through Dun Algaz from Loch Modan, or use an available boat to Menethil Harbor. Take the safe road to the harbor.")
optional(g,"algaz-entry","Optional Dun Algaz approach",{468,455},"If arriving from Loch Modan, report to Mountaineer Rockgar and clear the offered Algaz Gauntlet work while crossing. Boat arrivals can bypass this detour.")
D:Group(g,"menethil-first","Menethil: coastal claws, crocolisks and regional introductions","pickup",{279,484,463,305,470})
cycle(g,"coastal-first","Menethil coast: claws and young crocolisk skins",{279,484},"Keep accepted ooze collection active while crossing the marsh later; do not farm the rare bag drop here.")
delivery(g,"greenwarden-intro","Find Rethiel the Greenwarden",463)
cycle(g,"greenwarden-paws","Greenwarden: clear nearby gnolls",{276})
cycle(g,"greenwarden-fire","Greenwarden: collect the gnoll flints",{277})
delivery(g,"excavation-find","Reach Whelgar's excavation team",305)
D:Group(g,"excavation-first-pickup","Excavation: first raptor hunt and relic collection","pickup",{294,299})
cycle(g,"ormer-first","Excavation outskirts: first Ormer hunt",{294},"Gather excavation relics while travelling between the raptor areas. Check the higher-level enemies before entering the central pit.")
delivery(g,"excavation-report","Report the excavation team's location to Menethil",306)
optional(g,"menethil-beta","Optional harbor deliveries and beta work",{469,98197,98282,98461},"Combine Daily Delivery and offered beta work with the marsh circuit. Unrequited Love is useful only if already accepted in Darkshore.")
D:Checkpoint(g,"wetlands-level24",24,"Finish the coastal and first raptor circuits before deeper excavation and shipwreck work.")
cycle(g,"ormer-second","Excavation: second raptor hunt",{295})
D:Group(g,"relics-return","Return the completed excavation relics","turnin",{299})
cycle(g,"greenwarden-blisters","Marsh circuit: clear the fen creepers",{275})
D:Group(g,"ooze-return","Return the ooze bag when it drops","turnin",{470},nil,"The bag can take time to drop. Use Skip if repeated ooze farming is poor value; this collection is not a class unlock.")
cycle(g,"statuette-first","Coastal hovels: inspect the damaged crate",{281})
cycle(g,"statuette-second","Continue the coastal goods search",{284})
cycle(g,"statuette-third","Search the final coastal hovel",{285})
delivery(g,"statuette-return","Return the statuette to Karl Boran",286)
cycle(g,"third-fleet","Menethil: investigate the Third Fleet",{288},"Read the quest's current item requirement before leaving the harbor; purchase it locally if available.")
D:Group(g,"shipwreck-pickup","Take the Cursed Crew investigation","pickup",{289})
D:Checkpoint(g,"wetlands-level27",27,"Check the undead shipwreck enemies and raptor boss before attempting the later circuits.")
cycle(g,"cursed-crew","Western shipwrecks: clear the cursed crew",{289},"Plan a safe way out of the wrecks and watch breath if underwater. Group up or Skip if contested or dangerous.")
cycle(g,"lift-curse","Shipwrecks: lift the curse",{290})
delivery(g,"paleth-eye","Deliver the Eye of Paleth in Menethil",292)
optional(g,"eye-city","Optional Stormwind delivery",{293},"Take Cleansing the Eye when visiting Stormwind for class training; avoid a separate journey solely for this delivery.")
cycle(g,"ormer-final","Excavation: finish Ormer's raptor hunt",{296},"Survey Sarltooth's level and nearby pulls. Skip or group if this fight is unsuitable.")
optional(g,"dragonmaw","Optional Dragonmaw and northern group work",{473,464,465,474,472,303,631,632,633,634},"Report to Captain Stoutfist if the Algaz work is done, then follow offered Dragonmaw stages in order. Nek'rosh, Dun Modr and parts of Thandol Span can require a group. The span leads into Arathi rather than supplying guaranteed solo XP here.")
D:ClassStop(g,"wetlands-train28","Combine class training with any accepted Stormwind or Ironforge delivery. Shaman Water Totem work is a critical class detour across several regions, not a local Wetlands-only quest.")
D:Finish(g,"wetlands","At 30, choose your next regional route when available. Duskwood or Ashenvale can supply unfinished quests if this circuit leaves you short; 30-40 guides are not installed.")

g=D:New("alliance-ashenvale-20-30","Ashenvale / Stonetalon 20-30","Ashenvale",{"NightElf","High Order Skyborne"},20,30)
entry(g,"Enter Ashenvale from Darkshore or your available transport route. Register Astranaar's flight point. Avoid Horde settlements.")
optional(g,"ashenvale-arrival","Optional Darkshore arrival deliveries",{990,976},"Hand in Trek to Ashenvale or Supplies to Auberdine if you already have them. Their preceding Darkshore chains are not required entry work for this guide.")
D:Group(g,"astranaar-first","Astranaar: coastal work and Raene's introduction","pickup",{1008,991,1054})
cycle(g,"bathran","Northern Ashenvale: Bathran's Hair",{1010})
delivery(g,"orendil-cure","Bring Orendil's cure to Astranaar",1020)
cycle(g,"elune-tear","Northern lake: retrieve Elune's Tear",{1033})
cycle(g,"stardust","Southern ruins: collect stardust",{1034})
delivery(g,"raene-teronis","Find Teronis for Raene's investigation",991)
cycle(g,"raene-return","Return Teronis' findings to Raene",{1023})
cycle(g,"zoram-strand","Western coast: clear the Zoram Strand",{1008})
cycle(g,"ancient-statuette","Western coast: retrieve Talen's statuette",{1007})
cycle(g,"ruuzel","Western coast: finish Talen's follow-up",{1009},"Check Ruuzel and nearby naga before pulling; this follow-up is more demanding than the first coastal collection.")
D:Group(g,"stonetalon-intro-pickup","Astranaar: take Stonetalon introductions","pickup",{1070,1056,1134})
delivery(g,"stonetalon-guard","Report to Kaela Shadowspear",1070)
delivery(g,"stonetalon-gaxim","Report to Gaxim Rustfizzle",1085)
cycle(g,"gnome-respite","Windshear area: help Gaxim",{1071})
cycle(g,"pridewings","Stonetalon: collect pridewing venom sacs",{1134})
delivery(g,"stonetalon-peak","Reach the Stonetalon Peak contact",1056)
optional(g,"stonetalon-city-detours","Optional Gaxim city-delivery chains",{1072,1073,1074,1075,1076,1077},"These branches visit Ironforge, Stormwind and Westfall. Combine them with class training if offered; follow each quest's prerequisites rather than making every delivery a mandatory trip.")
optional(g,"stonetalon-side-work","Optional Windshear and Charred Vale work",{1093,1094,1095,1096,1090,1092,1057,86574},"Take suitable local quests actually offered. Gerenzo's Orders includes an escort; Further Instructions visits the Barrens. Check enemy levels before Charred Vale or Gerenzo fights, and avoid Horde towns.")
D:ClassStop(g,"ashenvale-train24","Train useful abilities in Darnassus or your class city, then return to Astranaar. Combine city travel with accepted delivery branches.")
D:Checkpoint(g,"ashenvale-level24",24,"Complete accepted coast and Stonetalon work before the eastern furbolg and elemental circuits.")
delivery(g,"raene-shaeldryn","Visit Shael'dryn for Raene",1024)
cycle(g,"aggressive-defense","Astranaar surroundings: reduce the furbolg threat",{1025})
cycle(g,"culling-threat","Northern furbolg camp: cull the threat",{1054},"Check the named target's level and nearby adds before committing; Skip an unsafe camp.")
cycle(g,"elemental-bracers","Eastern Ashenvale: collect elemental bracers",{1016})
cycle(g,"mage-summoner","Eastern Ashenvale: stop the summoner",{1017},"Pull carefully and check the quest's current target. Do not assume the consumable reward is a permanent class unlock.")
D:Checkpoint(g,"ashenvale-level27",27,"The later Raene chain and eastern camps are harder. Add useful unfinished Duskwood or Wetlands work if you need more XP.")
cycle(g,"raene-first-components","Shael'dryn: first cleansing components",{1026})
cycle(g,"raene-second-components","Shael'dryn: second cleansing components",{1027})
cycle(g,"raene-shrine","Visit the hidden shrine",{1028})
delivery(g,"raene-shrine-return","Return from the shrine to Shael'dryn",1055)
delivery(g,"raene-astranaar-return","Report to Raene in Astranaar",1029)
delivery(g,"raene-krolg","Find Krolg for the cleansing chain",1030)
cycle(g,"raene-krolg-task","Carry out Krolg's cleansing task",{1045})
delivery(g,"raene-finish","Return the cleansing report to Raene",1046)
delivery(g,"kayneth-intro","Report to Kayneth Stillwind",4581)
cycle(g,"forsaken-disease","Eastern forests: investigate Forsaken diseases",{1011})
cycle(g,"fallen-sky-lake","Fallen Sky Lake: recover the requested item",{1035},"Check the lake enemies and safe exit before entering. This follows the earlier Pelturas chain.")
optional(g,"ashenvale-final-detours","Optional higher-level eastern camps",{1022,1012,1021,1031,1032},"Howling Vale, the insane druids and satyr branches are harder. Only take suitable offered quests; several targets are above this bracket and may require a group. These are not required to finish the regional circuit.")
D:Finish(g,"ashenvale","At 30, choose your next regional route when available. Finish useful accepted branches first; 30-40 guides are not installed.")
