local _, F = ...
local D = F.GuideDraft
-- Authored circuits; live quest state supplies counts. Beta extras are nonblocking.
local function cycle(g,key,label,ids,side,note)
    D:Group(g,key.."-pickup",label..": accept","pickup",ids,side,note)
    D:Group(g,key.."-objectives",label..": objectives together","objective",ids,side,note)
    D:Group(g,key.."-return",label..": batch turn-ins","turnin",ids,side,note)
end
local function entry(g,note)
    D:ClassStop(g,"entry-class",note.." Complete your level-10 class milestone first. Register the region's flight point and set a useful hearthstone manually. Next confirms this stop.")
end
local function redridge(g,prefix)
    D:ClassStop(g,prefix.."-train","Train useful abilities in your class city before travelling to Lakeshire. Combine training with any accepted city delivery; do not make separate trips for every errand.")
    D:Checkpoint(g,prefix.."-level15",15,"Finish nearby accepted quests before moving to Redridge. Arriving above 15 is fine; Auto checks completed quests, not a fixed starting level.")
    D:Group(g,prefix.."-gnoll-intro","Take Encroaching Gnolls on the Lakeshire approach","pickup",{244})
    D:Group(g,prefix.."-gnoll-report","Deliver the gnoll report in Lakeshire","turnin",{244})
    D:Group(g,prefix.."-pickup","Lakeshire: collect shared hunting and lake work","pickup",{246,125,92,3741},{98407,116})
    D:Group(g,prefix.."-hunting","Eastern road: gnolls, boars, condors and tarantulas together","objective",{246,92},{98407,127},"Keep the different goulash ingredients until the whole quest is ready. Skip a repeatedly dangerous camp rather than forcing a solo clear.")
    D:Group(g,prefix.."-lake","Lake loop: retrieve the tools and necklace","objective",{125,3741},nil,"Check your breath and hostile levels before diving. Retrieve the necklace from its lake container during the tools visit.")
    D:Group(g,prefix.."-return","Batch Lakeshire hunt and lake turn-ins","turnin",{246,125,92,3741},{98407})
    D:Group(g,prefix.."-bridge-pickup","Take The Everstill Bridge","pickup",{89})
    cycle(g,prefix.."-shoes","The Price of Shoes delivery",{118},nil,"Pair this Goldshire visit with training. Skip the delivery chain if you do not want another city journey.")
    D:Group(g,prefix.."-shoes-return-pickup","Take Return to Verner","pickup",{119})
    D:Group(g,prefix.."-verner-return","Return to Lakeshire","turnin",{119})
    D:Group(g,prefix.."-fish-pickup","Take Selling Fish at level 16","pickup",{127})
    D:Group(g,prefix.."-scales-pickup","Take Underbelly Scales","pickup",{122})
    D:Group(g,prefix.."-bridge-loop","Bridge, whelps and fish: finish the local circuit","objective",{89,122,127})
    D:Group(g,prefix.."-bridge-return","Return bridge materials, scales and fish","turnin",{89,122,127})
    D:Note(g,prefix.."-optional","Optional gear, errands and harder camps","Dry Times needs drinks from several towns: only finish it when those visits overlap your training route. Defer elite Blackrock camps and dungeon work unless you have a group. Compare usable rewards rather than item color alone.")
    g.steps[#g.steps].alongside={D:Task("objective",116,true),D:Task("turnin",116,true),D:Task("pickup",20,true),D:Task("objective",20,true),D:Task("turnin",20,true)}
end

local g=D:New("alliance-westfall-10-20","Westfall / Redridge 10-20","Westfall",{"Human","High Order Skyborne"},10,20)
entry(g,"Enter Westfall from Elwynn or the available Alliance transport route.")
D:Group(g,"furlbrow-pickup","Furlbrow farm: collect road errands","pickup",{36,151},{64,184,98021})
D:Group(g,"saldean-arrive","Deliver Westfall Stew at Saldean's farm","turnin",{36},{98021})
D:Group(g,"saldean-pickup","Saldean farm: shared wildlife and harvesters","pickup",{38,9,22},{92909,92910,92911})
D:Group(g,"sentinel-pickup","Sentinel Hill: first militia orders","pickup",{12,102,153},{92742,92744,92745})
D:Group(g,"north-loop","Northern farms: wildlife, harvesters and Defias together","objective",{12,151,102,153,38,22,9},{64,92909,92910,92911},"Bandanas share the militia's Defias kills. Collect oats, gnoll paws, and stew/liver ingredients from suitable lower-level local enemies before tackling the level 14-15 Harvest Watchers.")
D:Group(g,"north-farm-return","Return to the northern farms","turnin",{38,9,151,22},{64,184,92909,92910,92911})
D:Group(g,"militia-first-return","Return the first militia orders to Sentinel Hill","turnin",{12,102,153})
cycle(g,"militia-second","Second militia circuit",{13},{153,102},"These are different Defias ranks from the first orders. Follow your live quest objectives.")
D:Group(g,"militia-third-pickup","Take the final open-world militia orders","pickup",{14},{153,92747,92749})
D:Group(g,"moonbrook-loop","Moonbrook: militia and bandanas together","objective",{14},{153,92747,92749},"Pull carefully around buildings; defer the dungeon objectives. Native quest waypoints take priority for beta additions.")
D:Group(g,"moonbrook-return","Return the militia and accepted bandanas","turnin",{14},{153,92747,92749})
D:Checkpoint(g,"westfall-level14",14,"Finish accepted nearby hunts if below 14. The Defias investigation needs level 14; it includes several deliveries.")
cycle(g,"defias-redridge","Defias investigation: speak to Wiley in Lakeshire",{65},nil,"Use this journey to register Lakeshire's flight point. If you leave for Redridge now, select its later steps and use Skip for the remaining investigation.")
cycle(g,"defias-sentinel","Return Wiley's report to Sentinel Hill",{132})
cycle(g,"defias-stormwind","Defias investigation: Mathias in Stormwind",{135},nil,"Combine the city visit with class training and supplies.")
cycle(g,"defias-report","Return Mathias's report to Sentinel Hill",{141})
cycle(g,"defias-messenger","Intercept the Defias messenger",{142},nil,"Patrol competition can make this slow. Skip this branch if the messenger is heavily camped.")
cycle(g,"defias-traitor","Escort the Defias traitor",{155},nil,"Start only when the escort is available and safe. The dungeon finale is optional.")
D:Note(g,"westfall-optional","Optional coastal rewards and dungeon work","Keep coastal hunts for a shared beach circuit. Captain Sander's treasure starts from a dropped map; do not farm it solely for a low-value reward. The Deadmines finale is group content and does not block this route.")
g.steps[#g.steps].alongside={D:Task("pickup",152,true),D:Task("objective",152,true),D:Task("turnin",152,true),D:Task("pickup",104,true),D:Task("objective",104,true),D:Task("turnin",104,true)}
redridge(g,"westfall-redridge")
D:Finish(g,"westfall","At 20, choose Duskwood / Redridge, Wetlands or Ashenvale / Stonetalon 20-30 from the guide chooser.")

g=D:New("alliance-loch-modan-10-20","Loch Modan / Redridge 10-20","Loch Modan",{"Dwarf","Gnome","High Order Skyborne"},10,20)
entry(g,"Enter Loch Modan through the Dun Morogh pass.")
-- Keep the Fire Totem chain visible even after completion, skipping, or From.
for _, id in ipairs({94449,94465,94466,94467,94468}) do
    for _, kind in ipairs({"pickup","objective","turnin"}) do
        g.steps[#g.steps+1] = {id="shaman-fire:"..id..":"..kind,
            type=kind, questID=id, classes={"SHAMAN"}, minLevel=10,
            critical=true, criticalReason="Fire Totem", unlockChain=true,
            text="Call of Fire", note="Shaman Fire Totem chain: Ironforge or Kharanos, eastern Dun Morogh, then Loch Modan. Follow the quest's current instructions."}
    end
end
-- Quest 912 has no evidenced playable actions or locations; retain its
-- reference record for research, but do not schedule it as a quest route.
cycle(g,"south-troggs","South gate: first trogg orders",{224},{86585})
D:Group(g,"thelsamar-pickup","Thelsamar: wildlife work and Stormpike's introduction","pickup",{418,416,1339},{86585})
D:Group(g,"thelsamar-hunts","West shore: rats and sausage ingredients together","objective",{418,416})
D:Group(g,"thelsamar-return","Batch Thelsamar hand-ins","turnin",{418,416},{86585})
D:Group(g,"stormpike-arrive","Deliver Mountaineer Stormpike's Task at the northern guard tower","turnin",{1339})
D:Group(g,"stormpike-pickup","Northern guard tower: mine supplies","pickup",{307},{1338,86667})
D:Group(g,"silverstream-loop","Silver Stream Mine: recover Miners' Gear","objective",{307},{86667},"The gear is collected from containers. Mountaineer Stormpike's Task was the delivery to the tower; it does not require kobold ears.")
D:Group(g,"stormpike-return","Return the mine supplies to the northern guard tower","turnin",{307},{86667})
cycle(g,"south-second","South gate: second trogg ranks",{237})
cycle(g,"south-third","South gate: collect the shaman symbols",{263},{86585})
D:Checkpoint(g,"loch-level13",13,"Finish nearby active hunts before the eastern excavation. Check enemy levels before the timed lodge challenges.")
D:Group(g,"excavation-pickup","Eastern excavation: idols and supplies","pickup",{297,2038},{86613,86614,436})
D:Group(g,"excavation-loop","Eastern shore: idols and Bingles' scattered supplies","objective",{297,2038},{86613,86614})
D:Group(g,"excavation-return","Return excavation idols and Bingles' supplies","turnin",{297,2038},{86613,86614,436})
D:Group(g,"lodge-pickup","Farstrider Lodge: crocolisks and optional timed hunt","pickup",{385},{257,86758})
D:Group(g,"lodge-loop","Eastern wildlife circuit","objective",{385},{257,86758},"Accept the timed hunt only when ready to begin. It is optional and its XP is excluded from the required route.")
D:Group(g,"lodge-return","Return lodge hunts","turnin",{385},{257,86758})
cycle(g,"lodge-challenge","Optional second timed hunting challenge",{}, {258},"Skip if the timer or enemy levels are unsuitable. This follow-up requires the first timed hunt.")
cycle(g,"south-final","Optional named trogg pack",{}, {217},"Grawmug, Gnasher and Brawler are named enemies, not another batch of ordinary trogg ranks. Take this detour only when safe or with help.")
D:ClassStop(g,"loch-city","Use your flight point for Ironforge training. Pair accepted excavation supply deliveries with this visit; long supply and dam chains are optional.")
D:Group(g,"stormpike-city","Optional Stormwind delivery: Stormpike's Order","turnin",{}, {1338},"Deliver the request to Furen Longbeard only if a Stormwind visit suits your route. This is not an Ironforge hand-in.")
D:Note(g,"loch-gear","Optional lodge rewards and escorts","Vyrin's Revenge is gated behind the timed hunts and asks for a dangerous named bear. Do it with help if its usable reward is valuable; skip repeated deaths. Protecting the Shipment is optional escort work.")
g.steps[#g.steps].alongside={D:Task("pickup",271,true),D:Task("objective",271,true),D:Task("turnin",271,true),D:Task("pickup",531,true),D:Task("turnin",531,true),D:Task("pickup",309,true),D:Task("objective",309,true),D:Task("turnin",309,true)}
redridge(g,"loch-redridge")
D:Finish(g,"loch","At 20, choose Duskwood / Redridge, Wetlands or Ashenvale / Stonetalon 20-30 from the guide chooser.")

g=D:New("alliance-darkshore-10-20","Darkshore 10-20","Darkshore",{"Night Elf","High Order Skyborne"},10,20)
entry(g,"Arrive in Auberdine from the available Alliance route.")
D:Group(g,"auberdine-pickup","Auberdine: coastal work and first introductions","pickup",{983,954,2118,984,3524,963,958},{1141})
D:Group(g,"south-coast","South beach: crawlers and washed-ashore remains","objective",{983,3524},{1141})
D:Group(g,"buzzbox-first-return","Use Buzzbox 827 south of town","turnin",{983})
D:Group(g,"buzzbox-second-pickup","Take Buzzbox 411","pickup",{1001})
D:Group(g,"bashalaran-intro","Speak to Asterion at Bashal'Aran","turnin",{954})
cycle(g,"bashalaran-first","Bashal'Aran: collect Grell Earrings",{955})
cycle(g,"bashalaran-second","Bashal'Aran: retrieve the seal",{956})
D:Group(g,"bashalaran-south-pickup","Take the Ameth'Aran follow-up","pickup",{957})
D:Group(g,"scout-threat","Scout the furbolg threat and trap a plagued bear","objective",{984,2118},{1001})
D:Group(g,"auberdine-first-return","Return scouting, trapped bear and washed-ashore remains","turnin",{984,2118,3524})
D:Group(g,"washed-followup-pickup","Take the Sea Turtle Remains follow-up","pickup",{4681})
D:Group(g,"washed-followup-loop","Retrieve the Sea Turtle Remains near Auberdine","objective",{4681})
D:Group(g,"auberdine-next-pickup","Take the furbolg and infected wildlife follow-ups","pickup",{985,2138,4761},{963})
D:Group(g,"river-introduction","Deliver the river introduction in town","turnin",{4761})
D:Group(g,"river-pickup","Take The Cliffspring River","pickup",{4762})
D:Group(g,"ametharan-pickup","Ameth'Aran: take the nearby ruins quest","pickup",{953})
D:Group(g,"ametharan-loop","Ameth'Aran: relics, flame and Anaya's pendant","objective",{953,957,958,963})
D:Group(g,"ametharan-return","Return the ruins work and Asterion's follow-up","turnin",{953,957})
D:Group(g,"south-beached-pickup","Southern shore: investigate the beached turtle","pickup",{4722})
D:Group(g,"south-beached-remains","Collect the beached turtle's remains","objective",{4722})
D:Group(g,"furbolg-loop","Nearby furbolgs and infected wildlife together","objective",{985,2138})
D:Group(g,"auberdine-second-return","Batch Auberdine hand-ins","turnin",{985,2138,958,963,4681,4722})
D:Checkpoint(g,"darkshore-level12",12,"Finish accepted local objectives before the crystal and northern cave loops.")
D:Group(g,"north-pickup","Auberdine: crystal, cave and lost-master work","pickup",{4811,947,986},{982,98025,98042})
D:Group(g,"north-shore-loop","North shore: threshers and river sample","objective",{1001,4762},{982})
D:Group(g,"north-beached-pickup","Northern shore: investigate the beached sea creature","pickup",{4723})
D:Group(g,"north-beached-remains","Collect the northern sea creature's bones","objective",{4723})
D:Group(g,"buzzbox-second-return","Return at Buzzbox 411","turnin",{1001})
D:Group(g,"buzzbox-third-pickup","Take Buzzbox 323","pickup",{1002})
D:Group(g,"north-cave-crystal","Northern cave and red-crystal circuit","objective",{947,4811},{1002},"Caves and underwater wrecks can be slow or dangerous. Deep Ocean, Vast Sea is optional; leave it if repeated drownings outweigh the reward.")
D:Group(g,"north-return","Return the northern circuit to Auberdine","turnin",{947,4811,4762,4723},{982,98025,98042})
D:Group(g,"crystal-water-pickup","Take As Water Cascades","pickup",{4812})
D:Group(g,"crystal-water","Fill the vessel and revisit the crystal","objective",{4812})
D:Group(g,"crystal-water-return","Return As Water Cascades","turnin",{4812})
cycle(g,"crystal-fragments","Retrieve the crystal fragments",{4813})
D:Group(g,"north-buzzbox","Collect moonstalker fangs along the road","objective",{1002},{986})
D:Group(g,"buzzbox-third-return","Use Buzzbox 323 on the northern road","turnin",{1002})
D:Group(g,"buzzbox-final-pickup","Take Buzzbox 525 for the southern circuit","pickup",{1003})
D:ClassStop(g,"darkshore-train","Pair a city training visit with supplies before the southern circuit. Keep ready hand-ins for the same return trip.")
D:Group(g,"onu-pickup","Take Onu's introduction","pickup",{948},{952})
D:Group(g,"onu-arrive","Visit Onu in the Grove of the Ancients","turnin",{948},{952})
D:Group(g,"glaive-pickup","Take The Master's Glaive","pickup",{944})
D:Group(g,"south-loop","Southern road: glaive and thistle bears","objective",{944,1003},{986})
D:Group(g,"glaive-handoff","Complete The Master's Glaive handoff","turnin",{944})
cycle(g,"twilight-camp","Investigate the Twilight Camp",{949},nil,"Interact with the quest object offered by the preceding glaive step; use the native waypoint.")
cycle(g,"onu-return","Return the camp report to Onu",{950})
D:Group(g,"mathystra-pickup","Take Mathystra Relics","pickup",{951},{993})
D:Group(g,"south-buzzbox-return","Return thistle bears at Buzzbox 525","turnin",{1003})
D:Group(g,"far-south-beached-pickup","Far southern shore: investigate the three beached creatures","pickup",{4731,4732,4733})
D:Group(g,"far-south-beached-remains","Collect the southern creatures' remains and marked box","objective",{4731,4732,4733},nil,"Use the separate carcasses along the southern coast. These are object-looting objectives, not three assumed combat hunts.")
D:Group(g,"far-south-beached-return","Return the southern beach finds in Auberdine","turnin",{4731,4732,4733})
D:Group(g,"final-coast-pickup","Auberdine: Fruit of the Sea and the tower introduction","pickup",{1138,965})
D:Group(g,"tower-darkshore-arrive","Deliver the tower introduction to Balthule Shadowstrike","turnin",{965})
cycle(g,"tower-darkshore-parchment","Tower outskirts: recover four Worn Parchments",{966},nil,"Fight the cultists outside the tower. Leave the dangerous interior and later Ashenvale continuation for their own guides.")
D:Group(g,"final-coast-crabs","Collect Fine Crab Chunks on the northern shore","objective",{1138})
D:Checkpoint(g,"darkshore-level17",17,"Finish active nearby work before the high-level northern ruins. Defer difficult escorts without a safe path or group.")
D:Group(g,"mathystra-loop","Northern ruins: collect the relics","objective",{951},{986,993})
D:Group(g,"final-coast-return","Return Fruit of the Sea in Auberdine on the way south","turnin",{1138})
D:Group(g,"mathystra-return","Return the relics to Onu","turnin",{951},{986,993})
D:Note(g,"darkshore-optional","Optional final hunts, gear and escorts","Murkdeep and difficult furbolg leaders are optional group/reward detours. The lost-master chain continues only after its earlier objectives. Take a nearby escort when safe; avoid waiting for it solely to fill the route.")
g.steps[#g.steps].alongside={D:Task("pickup",2139,true),D:Task("objective",2139,true),D:Task("turnin",2139,true),D:Task("pickup",4740,true),D:Task("objective",4740,true),D:Task("turnin",4740,true),D:Task("pickup",5321,true),D:Task("objective",5321,true),D:Task("turnin",5321,true)}
D:Finish(g,"darkshore","At 20, choose Duskwood / Redridge, Wetlands or Ashenvale / Stonetalon 20-30 from the guide chooser.")
