"""Supplement missing gathering coordinates from the installed Forever database."""
from pathlib import Path
from lupa.lua51 import LuaRuntime
from read_installed_questie import InstalledDB

root = Path(__file__).resolve().parents[1]
lua = LuaRuntime(unpack_returned_tuples=True)
lua.execute('F={}; function loadData(code) assert(loadstring(code))("ForeverRested",F) end')
for name in ('AllianceQuestData.lua', 'Alliance_20_30_QuestData.lua'):
    lua.globals().loadData((root/'Guides'/name).read_text())
records = lua.globals().F.AllianceQuestData
zones = {}
for _, record in records.items():
    for _, point in record.locations.items():
        if point.areaID and point.zone:
            zones[point.areaID] = point.zone
db = InstalledDB(root.parent/'QuestieDB/QuestieDB_Forever.toc')
def entity(kind, identity):
    try:
        value = db.entity(kind, identity)
        return value if isinstance(value, dict) else {}
    except TypeError:
        return {}  # Empty encoded entity.
def quote(text):
    return '"'+text.replace('\\','\\\\').replace('"','\\"')+'"'
lines = ['local _, F = ...', '-- Approximate object gathering areas from installed Forever QuestieDB.',
         '-- Generated by tools/build_object_locations.py; no runtime Questie dependency.']
count = 0
for identity, record in sorted(records.items()):
    quest = entity('Quest', identity)
    objectives = quest.get(10, {})
    objectives = objectives.get(3, []) if isinstance(objectives, dict) else []
    for objective in objectives:
        item = entity('Item', objective[0])
        name = item.get(1)
        if not name:
            continue
        existing = [p for _, p in record.locations.items() if p.role in ('requirement','sourcerequirement')]
        if any(p.x is not None and (p.item == name or len(objectives) == 1) for p in existing):
            continue
        points = {}
        for object_id in item.get(3, []):
            obj = entity('Object', object_id)
            spawn_table = obj.get(4, {})
            for area, spawns in (spawn_table.items() if isinstance(spawn_table, dict) else []):
                if area in zones:
                    points.setdefault(area, []).extend(p for p in spawns if 0 < p[0] <= 100 and 0 < p[1] <= 100)
        for area, spawns in sorted(points.items()):
            if not spawns:
                continue
            x = sum(p[0] for p in spawns)/len(spawns)/100
            y = sum(p[1] for p in spawns)/len(spawns)/100
            lines.append(f'table.insert(F.AllianceQuestData[{identity}].locations, {{role="sourcerequirement", item={quote(name)}, name={quote(name+" gathering area")}, zone={quote(zones[area])}, areaID={area}, x={x:.6f}, y={y:.6f}, approximate=true}})')
            count += 1
(root/'Guides/Alliance_ObjectLocations.lua').write_text('\n'.join(lines)+'\n')
print(f'Added {count} gathering areas')
