"""Refresh reviewed 20-30 recovery spawns from installed Forever QuestieDB."""
from pathlib import Path
from read_installed_questie import InstalledDB
from refresh_quest_data import lua as serialize

ROOT=Path(__file__).resolve().parents[1]

def main():
    base=ROOT/'tests/validate.py'
    setup=base.read_text().split("lua.execute(r'''",2)
    ns={'__file__':str(base)}
    exec(setup[0]+"lua.execute(r'''"+setup[1],ns)
    data=ns['lua'].globals().F.Audit2030Recovery
    records={key:{k:v for k,v in row.items()} for key,row in data.items()}
    db=InstalledDB(ROOT.parent/'QuestieDB/QuestieDB_Forever.toc')
    for key,npc_id in {'alliance-kalimdor-20-24':3743,'alliance-kalimdor-27-30':3825}.items():
        npc=db.entity('Npc',npc_id)
        assert npc.get(6,0)==0
        x,y=npc[7][331][0]
        updated={'name':npc[1],'npcID':npc_id,'minLevel':npc[4],'maxLevel':npc[5],
                 'zone':'Ashenvale','x':x/100,'y':y/100}
        if key.endswith('20-24'):
            updated['early']=records[key].get('early',records[key])
        records[key]=updated
    (ROOT/'Guides/Alliance_20_30_Recovery.lua').write_text(
        'local _,F=...\n-- Reviewed normal enemies; generated by tools/build_recovery_locations.py.\n'
        'F.Audit2030Recovery='+serialize(records)+'\n',encoding='utf-8')

if __name__=='__main__':main()
