"""Generate narrow runtime corrections from reviewed Questie NPC location findings."""
import argparse
import json
from pathlib import Path

from read_installed_questie import InstalledDB
from refresh_quest_data import lua

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'Data/QUESTIE_NPC_CORRECTIONS.json'
OUTPUT = ROOT / 'Guides/Alliance_QuestieNPCCorrections.lua'


def all_points(npc):
    raw = npc.get(7) or {}
    areas = raw if isinstance(raw, dict) else {npc.get(9): raw[0]} if raw and npc.get(9) else {}
    for area, points in areas.items():
        for x, y in points:
            yield area, x/100, y/100
    paths = npc.get(8) or {}
    if isinstance(paths, dict):
        for area, routes in paths.items():
            for route in routes:
                for x, y in route:
                    yield area, x/100, y/100


def generate():
    source = json.loads(SOURCE.read_text(encoding='utf-8'))
    db = InstalledDB(ROOT.parent / 'QuestieDB/QuestieDB_Forever.toc')
    if source['questieSHA256'] != db.sha256:
        raise ValueError('Installed QuestieDB changed; review the NPC corrections again')
    reference = json.loads((ROOT / 'Data/alliance-reference.json').read_text(encoding='utf-8'))['quests']
    zones = {point['areaID']: point['zone'] for quest in reference.values()
             for point in quest.get('locations', []) if point.get('areaID') and point.get('zone')}
    corrections = {}
    for row in source['corrections']:
        npc = db.entity('Npc', row['npcID'])
        points = list(all_points(npc))
        if not points:
            raise ValueError(f"No Questie spawn for NPC {row['npcID']}")
        same_area = [p for p in points if p[0] == row.get('areaID')]
        candidates = same_area or points
        area, x, y = min(candidates, key=lambda p: (p[1]-row.get('x', 0))**2+(p[2]-row.get('y', 0))**2)
        if area not in zones:
            raise ValueError(f'Unknown Questie area {area} for NPC {row["npcID"]}')
        correction = {'new': {'role': row['role'], 'entityType': 1, 'entityID': row['npcID'],
                              'name': npc[1], 'areaID': area, 'zone': zones[area],
                              'x': round(x, 5), 'y': round(y, 5), 'approximate': True,
                              'source': 'installed Forever QuestieDB',
                              'sourceSHA256': db.sha256}}
        if 'areaID' in row:
            correction['old'] = {k: row[k] for k in ('role', 'areaID', 'x', 'y')}
            correction['old']['npcID'] = row.get('oldNPCID', row['npcID'])
        corrections.setdefault(row['questID'], []).append(correction)
    lines = ['local _,F=...', '-- Generated by tools/build_questie_npc_corrections.py.',
             'local corrections=' + lua(corrections),
             'for questID,entries in pairs(corrections) do',
             ' local record=F.AllianceQuestData[questID] or F.ClassicQuestPolicy.records[questID]',
             ' if record and record.locations then',
             '  for _,entry in ipairs(entries) do',
             '   local old=entry.old',
             '   if old then',
             '    for i=#record.locations,1,-1 do',
             '     local p=record.locations[i]',
             '     if p.role==old.role and p.entityType==1 and p.entityID==old.npcID',
             '      and p.areaID==old.areaID and math.abs((p.x or -1)-old.x)<0.000001',
             '      and math.abs((p.y or -1)-old.y)<0.000001 then',
             '      table.remove(record.locations,i)',
             '     end',
             '    end',
             '   end',
             '   local present=false',
             '   for _,p in ipairs(record.locations) do',
             '    if p.role==entry.new.role and p.entityID==entry.new.entityID',
             '     and p.areaID==entry.new.areaID and math.abs((p.x or -1)-entry.new.x)<0.000001',
             '     and math.abs((p.y or -1)-entry.new.y)<0.000001 then present=true;break end',
             '   end',
             '   if not present then record.locations[#record.locations+1]=entry.new end',
             '  end',
             ' end',
             'end']
    OUTPUT.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'Questie NPC corrections: {sum(map(len, corrections.values()))} pins across {len(corrections)} quests')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--update-source', action='store_true')
    args = parser.parse_args()
    if args.update_source:
        report = json.loads((ROOT / 'Data/QUESTIE_NPC_LOCATION_AUDIT.json').read_text(encoding='utf-8'))
        source = json.loads(SOURCE.read_text(encoding='utf-8'))
        if source['questieSHA256'] != report['questieSHA256']:
            raise ValueError('QuestieDB changed; review the correction source')
        db = InstalledDB(ROOT.parent / 'QuestieDB/QuestieDB_Forever.toc')
        corrections = [r for r in source['corrections'] if list(all_points(db.entity('Npc', r['npcID'])))]
        seen = {(r['questID'], r['role'], r['npcID'], r.get('areaID'), r.get('x'), r.get('y'))
                for r in corrections}
        for finding in report['issues']:
            kind = finding['kind']
            if kind in ('distant-from-questie-spawn', 'no-questie-spawn-in-area'):
                row = dict(questID=finding['questID'], role=finding['role'], npcID=finding['npcID'],
                           areaID=finding['areaID'], x=finding['recordedXY'][0], y=finding['recordedXY'][1])
            elif kind == 'wrong-quest-actor' and len(finding['expectedNPCs']) == 1:
                row = dict(questID=finding['questID'], role=finding['role'],
                           npcID=finding['expectedNPCs'][0], oldNPCID=finding['npcID'],
                           areaID=finding['areaID'], x=finding['recordedXY'][0], y=finding['recordedXY'][1])
            elif kind == 'missing-questie-actor-pin' and len(finding['expectedNPCs']) == 1:
                if any(r['questID'] == finding['questID'] and r['role'] == finding['role']
                       and r['npcID'] == finding['expectedNPCs'][0] for r in corrections):
                    continue
                row = dict(questID=finding['questID'], role=finding['role'],
                           npcID=finding['expectedNPCs'][0])
            else:
                continue
            if not list(all_points(db.entity('Npc', row['npcID']))):
                continue
            key = (row['questID'], row['role'], row['npcID'], row.get('areaID'), row.get('x'), row.get('y'))
            if key not in seen:
                corrections.append(row)
                seen.add(key)
        SOURCE.write_text(json.dumps({'questieSHA256': report['questieSHA256'],
                                      'corrections': corrections}, indent=2)+'\n', encoding='utf-8')
    generate()
