"""Fetch factual Forever quest fields for authored 20-30 routes; no quest prose."""
import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import runpy
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--use-cache", action="store_true")
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)
    extract = runpy.run_path(str(ROOT / "tools/build_alliance_reference.py"))["extract"]
    decode = runpy.run_path(str(ROOT / "tools/build_alliance_reference.py"))["decode_after"]
    serialize = runpy.run_path(str(ROOT / "tools/refresh_quest_data.py"))["lua"]
    manifest = json.loads((ROOT / "Data/alliance-20-30-quests.json").read_text())
    ids = sorted({id for group in manifest["regions"].values() for id in group})
    water = set(manifest["regions"]["shaman-water"])

    def load(id):
        path = args.cache / f"{id}.html"
        if not args.use_cache or not path.exists():
            if args.use_cache:
                raise FileNotFoundError(path)
            data = urlopen(Request(f"https://www.wowhead.com/forever/quest={id}",
                                   headers={"User-Agent": "Mozilla/5.0"}), timeout=30).read()
            path.write_bytes(data)
        text = path.read_text(encoding="utf-8")
        record = extract(id, text, {id: {"SHAMAN"}} if id in water else {})
        if record.get("side") == 2:
            raise ValueError(f"Horde quest in Alliance manifest: {id}")
        record["retrievedAt"] = datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat()
        # Money is factual metadata, not a measured reward at the player's level.
        raw = decode(text, f"$.extend(g_quests[{id}], ")
        if raw.get("money"):
            record["rewardMoney"] = raw["money"]
        if id in water:
            objective = {94499: ("Redridge Mountains", "Stonewatch Falls"),
                         94500: ("Ashenvale", "Astranaar lake"),
                         94502: ("Westfall", "Stendel's Pond near Moonbrook")}.get(id)
            if objective:
                record["locations"] = [point for point in record["locations"] if point.get("role") not in ("requirement", "sourcerequirement")]
                record["locations"].append({"role": "requirement", "zone": objective[0], "name": objective[1], "approximate": True})
            record["routeNote"] = {
                94495: "Visit Norric Lochthane in Loch Modan, then Hervdana Saegrund in the Wetlands.",
                94497: "Fill the brown waterskin below Hervdana's waterfall and return to her.",
                94499: "Fill the red waterskin at Stonewatch Falls in Redridge, then return to Hervdana.",
                94500: "Fill the blue waterskin at Astranaar in Ashenvale, then return to Hervdana.",
                94501: "Bring the pure water to Norric in Loch Modan and keep the supplied items.",
                94502: "Use the sapta and cleanse the corruption at Stendel's Pond near Moonbrook in Westfall. Follow the shrine instructions.",
                94503: "Speak to the Minor Manifestation of Water at the Westfall shrine before leaving.",
                94505: "Bring the shard back to Norric in Loch Modan for the Water Totem.",
            }[id]
            # The shared elemental NPC mapper inherits Horde coordinates.
            # Alliance quest instructions explicitly place this spirit in Westfall.
            if id in (94503, 94505):
                role = "end" if id == 94503 else "start"
                record["locations"] = [point for point in record["locations"] if point.get("name") != "Minor Manifestation of Water"]
                record["locations"].append({"role": role, "name": "Minor Manifestation of Water", "zone": "Westfall", "approximate": True})
        return id, record, hashlib.sha256(path.read_bytes()).hexdigest()

    records, checksums = {}, {}
    with ThreadPoolExecutor(max_workers=4) as pool:
        for id, record, checksum in pool.map(load, ids):
            records[id], checksums[str(id)] = record, checksum
    payload = {"schemaVersion": 1, "compiledAt": datetime.now(timezone.utc).isoformat(),
               "game": "forever", "kind": "public-reference-not-live-build-verified",
               "checksums": checksums, "quests": records}
    (ROOT / "Data/alliance-20-30-reference.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    source = "local _, F = ...\n-- Factual supplement; generated by tools/build_20_30_reference.py.\n"
    source += "-- Standard Classic map IDs; Navigation validates each native map name.\n"
    source += "F.AllianceZoneMaps.Duskwood=1431; F.AllianceZoneMaps.Wetlands=1437\n"
    source += "F.AllianceZoneMaps.Ashenvale=1440; F.AllianceZoneMaps['Stonetalon Mountains']=1442\n"
    for id, record in sorted(records.items()):
        source += f"F.AllianceQuestData[{id}] = " + serialize(record) + "\n"
    (ROOT / "Guides/Alliance_20_30_QuestData.lua").write_text(source, encoding="utf-8")
    print(f"Compiled {len(records)} sourced quest references for Alliance 20-30 and Water Totem.")


if __name__ == "__main__":
    main()
