"""Refresh reviewed 20-30 recovery spawns from installed Forever QuestieDB."""
from pathlib import Path
from read_installed_questie import InstalledDB
from refresh_quest_data import lua as serialize

ROOT=Path(__file__).resolve().parents[1]

def main():
    from lupa.lua51 import LuaRuntime
    runtime=LuaRuntime(unpack_returned_tuples=True)
    holder=runtime.table()
    source=(ROOT/'Guides/Alliance_20_30_Recovery.lua').read_text(encoding='utf-8')
    runtime.execute('return function(F)\n'+source.replace('local _,F=...','',1)+'\nend')(holder)
    data=holder.Audit2030Recovery
    records={key:{k:v for k,v in row.items()} for key,row in data.items()}
    db=InstalledDB(ROOT.parent/'QuestieDB/QuestieDB_Forever.toc')
    for key,npc_id in {'alliance-kalimdor-20-24':3743,'alliance-kalimdor-27-30':3825}.items():
        npc=db.entity('Npc',npc_id)
        assert npc.get(6,0)==0
        x,y=npc[7][331][0]
        updated={'name':npc[1],'npcID':npc_id,'minLevel':npc[4],'maxLevel':npc[5],
                 'zone':'Ashenvale','x':x/100,'y':y/100}
        records[key]=updated
    records['alliance-kalimdor-23-24']=dict(records['alliance-eastern-24-25'])
    records['alliance-kalimdor-24-25']=dict(records['alliance-eastern-22-24'])
    records['alliance-kalimdor-25-27-rebuild']=dict(records['alliance-kalimdor-24-27'])
    (ROOT/'Guides/Alliance_20_30_Recovery.lua').write_text(
        'local _,F=...\n-- Reviewed normal enemies; generated by tools/build_recovery_locations.py.\n'
        'F.Audit2030Recovery='+serialize(records)+'\n',encoding='utf-8')

if __name__=='__main__':main()
