"""Apply only exact, nearby Anniversary Questie NPC evidence to missing Forever pins."""
import json
import hashlib
from pathlib import Path

from audit_classic_npc_fallback import CLASSIC, SOD_NPCS, ERA_FIXES
from read_installed_questie import InstalledDB
from refresh_quest_data import lua

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / 'Data/CLASSIC_NPC_FALLBACK_EVIDENCE.json'
OUTPUT = ROOT / 'Guides/Alliance_ClassicNPCFallback.lua'


def main():
    evidence = json.loads(EVIDENCE.read_text(encoding='utf-8'))
    classic = InstalledDB(CLASSIC, expected_flavor='Vanilla')
    if evidence['anniversaryQuestieSHA256'] != classic.sha256:
        raise ValueError('Anniversary QuestieDB changed; review the fallback evidence')
    hashes = {'sod-npc-baseline': hashlib.sha256(SOD_NPCS.read_bytes()).hexdigest(),
              'classic-era-faction-correction': hashlib.sha256(ERA_FIXES.read_bytes()).hexdigest()}
    entries = evidence['entries']
    for row in entries:
        if hashes.get(row['evidenceKind']) != row['sourceSHA256']:
            raise ValueError('Anniversary correction source changed; review the fallback evidence')
    by_quest = {}
    for row in entries:
        by_quest.setdefault(row['questID'], []).append({k: v for k, v in row.items() if k != 'questID'})
    lines = ['local _,F=...', '-- Generated by tools/build_classic_npc_fallback.py; labeled Anniversary evidence.',
             'local evidence=' + lua(by_quest),
             'for questID,entries in pairs(evidence) do',
             ' local record=F.AllianceQuestData[questID] or F.ClassicQuestPolicy.records[questID]',
             ' if record and record.locations then',
             '  for _,entry in ipairs(entries) do',
             '   for _,p in ipairs(record.locations) do',
             '    if p.role==entry.role and p.entityType==1 and p.entityID==entry.npcID',
             '     and p.areaID==entry.areaID and math.abs((p.x or -1)-entry.oldXY[1])<0.000001',
             '     and math.abs((p.y or -1)-entry.oldXY[2])<0.000001 then',
             '     p.x=entry.newXY[1];p.y=entry.newXY[2]',
             '     p.source=entry.source;p.evidenceKind=entry.evidenceKind',
             '     p.sourceSHA256=entry.sourceSHA256',
             '    end',
             '   end',
             '  end',
             ' end',
             'end']
    OUTPUT.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(f'Anniversary fallback evidence: {len(entries)} pins across {len(by_quest)} quests')


if __name__ == '__main__':
    main()
