"""Supplement evidenced action destinations; never copy the guide's region."""
import json
from pathlib import Path
from read_installed_questie import InstalledDB
from refresh_quest_data import lua as serialize
ROOT=Path(__file__).resolve().parents[1]
DELIVERIES={65,118,132,135,141,184,223,293,401,468,469,472,473,631,632,634,950,990,993,1021,1072,1074,1075,1077,1092,1094,1095,4495,4722,4723,4731,4732,4733,4813}
# Reviewed Forever objective text explicitly instructs delivery/dialogue here.
DELIVERIES.update({86613,86614,92644,92698,92860,92880,92881,92910,93089,93320,93958,94484,98461,99260})
SEARCH_DESTINATIONS={95,281,284,285,949,1028}
ESCORTS={155,309,976}

def main():
    ref=json.loads((ROOT/'Data/alliance-reference.json').read_text(encoding='utf-8'))['quests']
    db=InstalledDB(ROOT.parent/'QuestieDB/QuestieDB_Forever.toc')
    zones={int(p['areaID']):p['zone'] for q in ref.values() for p in q.get('locations',[]) if p.get('areaID') and p.get('zone')}
    missing=json.loads((ROOT/'Data/ACTION_LOCATION_REVIEW.json').read_text())['missing']
    ids={r['questID'] for r in missing}
    results={}
    def points(kind,identity,role,item=None):
        entity=db.entity(kind,identity);spawns=entity.get(7 if kind=='Npc' else 4,{}) or {}
        if isinstance(spawns,list):spawns={i+1:v for i,v in enumerate(spawns) if v}
        if not isinstance(spawns,dict):return []
        rows=[]
        for area,xy in spawns.items():
            if area not in zones:continue
            for x,y in xy[:1]:
                if 0<x<=100 and 0<y<=100:
                    rows.append(dict(role=role,entityType=1 if kind=='Npc' else 2,entityID=identity,
                        name=entity.get(1),zone=zones[area],areaID=area,x=x/100,y=y/100,
                        approximate=True,source='installed Forever QuestieDB',**({'item':item} if item else {})))
        return rows
    for identity in sorted(ids):
        q=ref.get(str(identity),{});locations=[]
        # Some chapter records predate the refreshed reference. Restore only
        # phase-specific pickup/delivery evidence, never reuse it for a hunt.
        for p in q.get('locations',[]):
            if p['role'] in ('start','end') and p.get('zone'):
                locations.append(dict(p,source=q.get('source', 'reviewed quest reference')))
        if identity in DELIVERIES or identity in SEARCH_DESTINATIONS:
            for p in q.get('locations',[]):
                if p['role']=='end' and p.get('x') is not None:
                    locations.append(dict(p,role='requirement',locationReason='Reviewed objective destination',source=q.get('source', 'reviewed quest reference')))
        else:
            for o in q.get('objectives',[]):
                if o.get('kind')=='npc':locations+=points('Npc',o['id'],'requirement')
                if o.get('kind')=='item':
                    item=db.entity('Item',o['id'])
                    for obj in item.get(3,[]):locations+=points('Object',obj,'sourcerequirement',o['name'])
                    for npc in item.get(2,[]):locations+=points('Npc',npc,'sourcerequirement',o['name'])
                    for npc in item.get(14,[]):locations+=points('Npc',npc,'sourcerequirement',o['name'])
            local=db.entity('Quest',identity);objective=local.get(10,{})
            if isinstance(objective,list):objective={i+1:v for i,v in enumerate(objective) if v}
            if isinstance(objective,dict):
                for kind,field in [('Npc',1),('Object',2)]:
                    for entry in objective.get(field,[]) or []:locations+=points(kind,entry[0],'requirement')
        if identity in ESCORTS:
            for p in q.get('locations',[]):
                if p['role']=='start' and p.get('x') is not None:
                    locations.append(dict(p,role='requirement',locationReason='Escort begins at its quest actor'))
        if locations:results[identity]=locations
    reviewed=json.loads((ROOT/'Data/ONLINE_ACTION_LOCATIONS.json').read_text(encoding='utf-8'))
    for identity,locations in reviewed['locations'].items():
        results.setdefault(int(identity),[]).extend(locations)
    lines=['local _,F=...','-- Generated by tools/build_action_locations.py from evidenced objective sources.',
           'local additions='+serialize(results),
           'for id,locations in pairs(additions) do',
           ' local record=F.AllianceQuestData[id] or F.ClassicQuestPolicy.records[id]',
           ' if record then for _,point in ipairs(locations) do record.locations[#record.locations+1]=point end end',
           'end']
    (ROOT/'Guides/Alliance_ActionLocations.lua').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print('Sourced action locations:',len(results),'quests')
if __name__=='__main__':main()
